# Site Settings
title: Roberta Glenn's Resume
email: bertaglenn21@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
twitter_username: bertaglenn
github_username:  rjglenn
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
