# Site Settings
title: Roberta Glenn's Resume
email: bertaglenn21@gmail.com
description: >
  A summary of my education and experience.
baseurl: "/resume"
url: "http://rjglenn.github.io"
twitter_username: bertaglenn
github_username:  rjglenn
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  projects:
      output: true

defaults:
    -scope:
     type: projects
   value:
      layout: page
